version: "3.9"  # optional since v1.27.0

services:
  web:
  container_name: alfa-react
  build:
    context:
      .
  ports:
    - "3000:5000"
  volumes:
    - .:/app
    - /app/node_modules
  args:
        serviceID: ${REACT_APP_SERVICE}
        templateID: ${REACT_APP_TEMPLATE_ID}
        publicKey: ${REACT_APP_PUBLIC_KEY}